"""use boolean organization status

Revision ID: 108e6a50b20d
Revises: cfb68c14d910
Create Date: 2026-09-08 13:44:36.283554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108e6a50b20d'
down_revision: Union[str, Sequence[str], None] = 'cfb68c14d910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('status', sa.Boolean(), nullable=False))
    op.alter_column('departments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('plants', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('workstations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workstations', 'status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('plants', 'status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('departments', 'status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('companies', 'status')
    # ### end Alembic commands ###
