"""add vehicle logs

Revision ID: 7459096f1b85
Revises: 
Create Date: 2026-08-26 11:33:09.435297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7459096f1b85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=150), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_track_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=True),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'session_id', 'vehicle_track_id', name='uq_vehicle_runtime_track')
    )
    op.create_index(op.f('ix_vehicle_logs_camera_id'), 'vehicle_logs', ['camera_id'], unique=False)
    op.create_index('ix_vehicle_logs_camera_plate_seen', 'vehicle_logs', ['camera_id', 'plate_number', 'last_seen_at'], unique=False)
    op.create_index(op.f('ix_vehicle_logs_first_seen_at'), 'vehicle_logs', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_vehicle_logs_last_seen_at'), 'vehicle_logs', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_vehicle_logs_plate_number'), 'vehicle_logs', ['plate_number'], unique=False)
    op.create_index(op.f('ix_vehicle_logs_session_id'), 'vehicle_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_logs_session_id'), table_name='vehicle_logs')
    op.drop_index(op.f('ix_vehicle_logs_plate_number'), table_name='vehicle_logs')
    op.drop_index(op.f('ix_vehicle_logs_last_seen_at'), table_name='vehicle_logs')
    op.drop_index(op.f('ix_vehicle_logs_first_seen_at'), table_name='vehicle_logs')
    op.drop_index('ix_vehicle_logs_camera_plate_seen', table_name='vehicle_logs')
    op.drop_index(op.f('ix_vehicle_logs_camera_id'), table_name='vehicle_logs')
    op.drop_table('vehicle_logs')
    # ### end Alembic commands ###
