"""add camera deployment metadata

Revision ID: 8a9bbbfcb868
Revises: 108e6a50b20d
Create Date: 2026-09-08 15:44:22.523882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9bbbfcb868'
down_revision: Union[str, Sequence[str], None] = '108e6a50b20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'cameras',
        sa.Column(
            'resolution',
            sa.String(length=50),
            nullable=True
        )
    )

    op.add_column(
        'cameras',
        sa.Column(
            'camera_model',
            sa.String(length=150),
            nullable=True
        )
    )

    op.add_column(
        'cameras',
        sa.Column(
            'plant_id',
            sa.Integer(),
            nullable=True
        )
    )

    op.add_column(
        'cameras',
        sa.Column(
            'department_id',
            sa.Integer(),
            nullable=True
        )
    )

    op.add_column(
        'cameras',
        sa.Column(
            'workstation_id',
            sa.Integer(),
            nullable=True
        )
    )

    # Existing cameras will automatically receive FALSE
    op.add_column(
        'cameras',
        sa.Column(
            'notifications_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )

    op.create_index(
        op.f('ix_cameras_department_id'),
        'cameras',
        ['department_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_cameras_plant_id'),
        'cameras',
        ['plant_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_cameras_workstation_id'),
        'cameras',
        ['workstation_id'],
        unique=False
    )

    op.create_foreign_key(
        None,
        'cameras',
        'workstations',
        ['workstation_id'],
        ['id']
    )

    op.create_foreign_key(
        None,
        'cameras',
        'departments',
        ['department_id'],
        ['id']
    )

    op.create_foreign_key(
        None,
        'cameras',
        'plants',
        ['plant_id'],
        ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_index(op.f('ix_cameras_workstation_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_plant_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_department_id'), table_name='cameras')
    op.drop_column('cameras', 'notifications_enabled')
    op.drop_column('cameras', 'workstation_id')
    op.drop_column('cameras', 'department_id')
    op.drop_column('cameras', 'plant_id')
    op.drop_column('cameras', 'camera_model')
    op.drop_column('cameras', 'resolution')
    # ### end Alembic commands ###
