"""add model path to ai profiles

Revision ID: 9b965fb71d28
Revises: 3bcb7d446d18
Create Date: 2026-09-10 10:23:40.940538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b965fb71d28'
down_revision: Union[str, Sequence[str], None] = '3bcb7d446d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_profiles', sa.Column('model_path_or_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_profiles', 'model_path_or_url')
    # ### end Alembic commands ###
