"""add ai profiles table

Revision ID: 9c28bc2695a6
Revises: 848622a029a1
Create Date: 2026-09-09 16:08:53.868548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c28bc2695a6'
down_revision: Union[str, Sequence[str], None] = '848622a029a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_profiles_id'), 'ai_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_ai_profiles_name'), 'ai_profiles', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_profiles_name'), table_name='ai_profiles')
    op.drop_index(op.f('ix_ai_profiles_id'), table_name='ai_profiles')
    op.drop_table('ai_profiles')
    # ### end Alembic commands ###
